live_config_reload = true

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# [shell]
# program = "/Users/macbookairm1/.oh-my-zsh/"

[window]
decorations = "Buttonless"
opacity = 0.6
blur = true
dynamic_padding = false
padding = { x = 8, y = 4}
startup_mode = "Windowed"
title = "Vycros"

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 500
unfocused_hollow = false
thickness = 0.18

[mouse]
hide_when_typing = true
